project:
  type: website
  render:
    - "**/index.qmd"
    - contributing.qmd
    - extensions.qmd


website:
  title: connect extensions
  navbar:
    left:
      - href: index.qmd
        text: Home
      - extensions.qmd
      - contributing.qmd

format:
  html:
    theme: cosmo
