[project]
name = "package-vulnerability-scanner"
version = "1.0.0"
description = "Scan for security vulnerabilities in your published content on Connect using Posit Package Manager. View an overview of CVEs (Common Vulnerabilities and Exposures) across all your apps, and get guidance on upgrading affected packages."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "starlette>=0.47.2",
    "httpx>=0.28.1",
    "posit-sdk>=0.10.0",
]
