project:
  type: website

website:
  title: "Connect Audits"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: unpublished.qmd
        text: Unpublished Content
      - href: runtime-versions.qmd
        text: Runtime Versions


format:
  html:
    theme: cosmo
    toc: true
    code-fold: true



