name: SDK Assistant Extension

on:
  pull_request:
    paths:
      - 'extensions/sdk-assistant/**'

env:
  EXTENSION_NAME: sdk-assistant

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create tar
        working-directory: ./extensions
        run: tar -czf $EXTENSION_NAME.tar.gz $EXTENSION_NAME

      - name: Upload extension tar
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.EXTENSION_NAME }}.tar.gz
          path: extensions/${{ env.EXTENSION_NAME }}.tar.gz
